//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by KNSoft.Precomp4C
//     KNSoft - KNSoft.Precomp4C
//     https://github.com/KNSoft/KNSoft.Precomp4C
//     Do not change this file manually
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include <KNSoft/Precomp4C/I18N/I18N.h>

enum
{
    Precomp4C_I18N_All_Administrator,
    Precomp4C_I18N_All_File,
    Precomp4C_I18N_All_RunAsAdmin,
    Precomp4C_I18N_All_AlwaysOnTop,
    Precomp4C_I18N_All_Refresh_F5,
    Precomp4C_I18N_All_SaveTree_Ctrl_S,
    Precomp4C_I18N_All_TextFileOfnFilter,
    Precomp4C_I18N_All_Help,
    Precomp4C_I18N_All_Homepage,
    Precomp4C_I18N_All_Highlight,
    Precomp4C_I18N_All_Properties,
    Precomp4C_I18N_All_Desktop,
    Precomp4C_I18N_All_Dialog,
    Precomp4C_I18N_All_Animation,
    Precomp4C_I18N_All_DateTimePicker,
    Precomp4C_I18N_All_HotKey,
    Precomp4C_I18N_All_Calendar,
    Precomp4C_I18N_All_ProgressBar,
    Precomp4C_I18N_All_ReBar,
    Precomp4C_I18N_All_StatusBar,
    Precomp4C_I18N_All_ToolBar,
    Precomp4C_I18N_All_ToolTips,
    Precomp4C_I18N_All_SliderBar,
    Precomp4C_I18N_All_UpDownControl,
    Precomp4C_I18N_All_Button,
    Precomp4C_I18N_All_ComboBox,
    Precomp4C_I18N_All_ExtendedComboBox,
    Precomp4C_I18N_All_EditControl,
    Precomp4C_I18N_All_HeaderControl,
    Precomp4C_I18N_All_ListBox,
    Precomp4C_I18N_All_IPAddressControl,
    Precomp4C_I18N_All_Hyperlink,
    Precomp4C_I18N_All_ListView,
    Precomp4C_I18N_All_NativeFont,
    Precomp4C_I18N_All_PageScroller,
    Precomp4C_I18N_All_ScrollBar,
    Precomp4C_I18N_All_StaticControl,
    Precomp4C_I18N_All_TabControl,
    Precomp4C_I18N_All_TreeView,
    Precomp4C_I18N_All_MDIClient,
};

EXTERN_C PRECOMP4C_I18N_TABLE Precomp4C_I18N_Table_All;
