//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by KNSoft.Precomp4C
//     KNSoft - KNSoft.Precomp4C
//     https://github.com/KNSoft/KNSoft.Precomp4C
//     Do not change this file manually
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include <KNSoft/Precomp4C/I18N/I18N.h>

enum
{
    Precomp4C_I18N_All_File,
    Precomp4C_I18N_All_Help,
    Precomp4C_I18N_All_Refresh_F5,
    Precomp4C_I18N_All_SaveTree_Ctrl_S,
    Precomp4C_I18N_All_Homepage,
    Precomp4C_I18N_All_TextFileOfnFilter,
};

EXTERN_C PRECOMP4C_I18N_TABLE Precomp4C_I18N_Table_All;
