//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by KNSoft.Precomp4C
//     KNSoft - KNSoft.Precomp4C
//     https://github.com/KNSoft/KNSoft.Precomp4C
//     Do not change this file manually
// </auto-generated>
//------------------------------------------------------------------------------

#include <KNSoft/Precomp4C/I18N/I18N.h>

PRECOMP4C_I18N_TABLE Precomp4C_I18N_Table_All = {
    (void*)0,
    0,
    2,
    {
        &(PRECOMP4C_I18N_LOCALE)
        {
            0xFFFF,
            L"en",
            {
                L"File",
                L"Help",
                L"Refresh	F5",
                L"Save Tree	Ctrl+S",
                L"Homepage",
            }
        },
        &(PRECOMP4C_I18N_LOCALE)
        {
            0xFFFF,
            L"zh-Hans",
            {
                L"文件",
                L"帮助",
                L"刷新	F5",
                L"保存树	Ctrl+S",
                L"主页",
            }
        },
    }
};

