#pragma once

#include "../AlleyWind.Core.inl"

#define DEFINE_CONSTANT(Value, Description) { Value, L###Value, (PCWSTR)Description }

EXTERN_C_START

typedef struct _AW_SYSCLASS_INFO
{
    CONST PCWSTR ClassName;
    PCWSTR DisplayName;
    PUI_VALUEEDITOR_CONSTANT StyleConsts;
    CONST ULONG StyleConstsCount;
} AW_SYSCLASS_INFO, * PAW_SYSCLASS_INFO;

VOID
AW_InitClassDatabase(VOID);

_Ret_maybenull_
PAW_SYSCLASS_INFO
AW_GetSysClass(
    _In_ PCWSTR ClassName);

typedef enum _AW_STYLE_VALUE_TYPE {
    AW_StyleType_Style,
    AW_StyleType_ExStyle,
    AW_StyleType_ClassStyle
} AW_STYLE_VALUE_TYPE, *PAW_STYLE_VALUE_TYPE;

HRESULT
AW_GetStyleValueConstants(
    _In_opt_ PAW_SYSCLASS_INFO SysClassInfo,
    _In_ AW_STYLE_VALUE_TYPE StyleType,
    _In_ LOGICAL IsChild,
    _Out_ PUI_VALUEEDITOR_CONSTANT* Consts,
    _Out_ PULONG ConstsCount);

FORCEINLINE
AW_ReleaseStyleValueConstants(
    _In_ AW_STYLE_VALUE_TYPE StyleType,
    _In_ PUI_VALUEEDITOR_CONSTANT Consts)
{
    if (StyleType == AW_StyleType_Style)
    {
        Mem_Free(Consts);
    }
}

typedef struct _AW_MESSAGE_CONSTANT_GROUP
{
    PUI_VALUEEDITOR_CONSTANT Constants;
    ULONG ConstantsCount;
} AW_MESSAGE_CONSTANT_GROUP, *PAW_MESSAGE_CONSTANT_GROUP;

extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_WM_Input;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_WM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_BM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_EM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_LB;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_CB;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_SBM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_STM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_CCM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_LVM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_TVM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_TCM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_HDM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_PBM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_TBM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_UDM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_TTM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_SB;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_RB;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_HKM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_MCM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_DTM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_BCM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_ACM;
extern AW_MESSAGE_CONSTANT_GROUP AW_DB_MSG_PGM;

EXTERN_C_END
